---

# If enabled this will configure a publisher for OCSP, OCSP signer key update service, OCSP publishing queue, OCSP publisher to the certificate profiles,
# create Peer connection, and create an auth key binding
use_external_va: false

# If enabled this will configure a Peer connection, and add the RA Peer role to EJBCA 
use_external_ra: false

# If enabled configures a Peer connection and key binding for Sign Server
use_external_ss: false

# Initialize a CA using configdump instead of the CLI
deploy_with_configdump: false
configdump_directory_structure: "{{ configdump_dir_structure }}"
configdump_import_files: "{{ configdump_files }}"

# Add publishers to the CA's in EJBCA
add_publshers_to_cas: true

# EJBCA version and deployment info
ejbca_version: 9.3.7
# If enabled Ansible controller is used as software repository for Apache Ant, EJBCA, and JDBC driver
use_local_repository: false
ejbca_remote_dir: ~/Downloads/PK-Software/ejbca_ce_9_3_7.zip
# EJBCA URL to download the zip release file
ejbca_software_url: https://github.com/Keyfactor/ejbca-ce/releases/download/r9.3.7/ejbca-ce-9.3.7.zip
ejbca_src_dir_name: ejbca_ce_9_3_7
ejbca_type: CA

# EJBCA Upgrade version
ejbca_upgrade_version: 9.3.7
# EJBCA Upgrade version URL to download the zip release file
ejbca_upgrade_software_url:
# Directory name of EJBCA Upgrade version
ejbca_upgrade_src_dir: ejbca_ce_9_3_7

# Variables to configure the Wildfly datasource for connecting to the applicable DB
appsrv_datasources:
  - jndi_name: "java:/EjbcaDS"
    pool_name: ejbcads
    database_connection_type: mariadb 
    database_driver_class: org.mariadb.jdbc.Driver
    database_jar_filename: mariadb-java-client.jar
    loadbalancing: false
    loadbalanced_hosts: []
    host: 127.0.0.1
    backup_host: ce01
    port: 3306
    database: ejbca
    user: ejbca-usr
    credential_ref: dbPassword
    password: "{{ encrypted_database_ejbcauser_password | default('RootFloridios123') }}"

# HSM Configuration
# Use softhsm for PKCS11
use_softhsm: true
use_ncipher: false
use_safenet_lunasa: false
# If true, allows running application server service via preload
ncipher_preload: false
# Path to the preload executable
preload_path: /opt/nfast/bin/preload
# HSM PKCS#11 shared library location
hsm_shared_library: /usr/lib64/libsofthsm2.so

ejbca_templated_properties_files:
  - src: cesecore.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/cesecore.properties"
  - src: database.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/database.properties"
  - src: ejbca.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/ejbca.properties"
  - src: web.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/web.properties"
  - src: mail.properties.j2
    dest: "{{ ejbca_home }}/../ejbca-custom/conf/mail.properties"
  - src: custom.properties.j2
    dest:  "{{ ejbca_home }}/../ejbca-custom/conf/custom.properties"

# Parameter specifying IP addresses authorized to access the healthcheck servlet
ejbca_conf_healtcheck_authorizedips: 127.0.0.1

# web.properties file - Set the hostname for configuring OAuth Reply URL
web_httpserver_hostname: "{{ httpd_identity_info.id_name }}"
    
# CA DN in Web format and filename used to configure cronjob for downloading CRL's
certification_authorities_crl_files:
  - crlfilename: "{{ organizationNameShort | lower }}-mgmtca.crl"
    cadn: "CN%3dManagementCA%2cOU%3dCertification+Authorities%2cO%3d{{ organizationNameCRL }}%2cC%3d{{ countryName }}"
  - crlfilename: "{{ organizationNameShort | lower }}-rootca-g1.crl"
    cadn: "CN%3d{{ organizationNameCRL }}+Root+CA+G1%2cOU%3dCertification+Authorities%2cO%3d{{ organizationNameCRL }}%2cC%3d{{ countryName }}"
  - crlfilename: "{{ organizationNameShort | lower }}-subca-g1.crl"
    cadn: "CN%3d{{ organizationNameCRL }}+Issuing+CA+G1%2cOU%3dCertification+Authorities%2cO%3d{{ organizationNameCRL }}%2cC%3d{{ countryName }}"

# Enrollment protocols to enable on EJBCA
enable_ejbca_protocols:
  - name: Certstore
  - name: CMP
  - name: CRLstore
  - name: OCSP
  - name: 'Public Web'
  - name: SCEP
  - name: Webdist
  - name: 'Web Service'

# CRL Update Service Worker Settings
crl_service_time_int: 1
crl_service_time_unit: HOURS

# Install MariaDB server and client for a standalone instance
mariadb_install_server: true

# Install only the Python MariaDB client for Ansible
mariadb_install_client: false
