# roles/mariadb/vars/Ubuntu.yml
---

mariadb_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql

mariadb_client_packages:
  - python3-pymysql

mariadb_srv_socket: "{{ mariadb_socket | default('/var/run/mysqld/mysqld.sock') }}"

mariadb_srv_config_network: "{{ mariadb_config_network | default('/etc/mysql/conf.d/network.cnf') }}"
mariadb_srv_config_server: "{{ mariadb_config_server | default('/etc/mysql/conf.d/server.cnf') }}"
mariadb_srv_config_custom: "{{ mariadb_config_custom | default('/etc/mysql/conf.d/custom.cnf') }}"
